[package]
name = "scene-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dcl-common = { path = "../../2dcl/dcl-common" }
rss = "2.0.6"
chrono = "0.4.26"